version: "3.8"
services:
  db:
    env_file:
      - .env
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./src/database/:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_PORT}:5432
networks:
  app-network:
    driver: bridge
