version: "3.7"
services:
  db:
    env_file: .env.testing
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./src/database/:/docker-entrypoint-initdb.d/
    ports:
      - 15432:5432
  db_testing:
    env_file: ./.env.testing
    image: mdillon/postgis:10
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 15433:5432
